### ISSUE TITLE
关于宽和高的损失函数

### ISSUE THREAD

**Issue by ZXTFINAL** [TowardsNorth/yolo_v1_tensorflow_guiyu#7]
按照论文的说法，为了能够更好识别小物体，计算宽高loss应该是两边的结果取开方计算，本工程内最终还是平方和，只是预先把预测w,h求了平方，不解（难道是认为预测出来的结果为 开方过的w，h吗，并且实际的标签并没有进行开方操作），不应该是预测和真实的均取开方再计算平方和误差吗

**Comment by Vandaci** [comment]
我觉得你可以自己改写一下
